import type { AppCrudFinding, AppScanReport, RiskLevel } from "../types.js";

/**
 * Builds the GitHub issue title/body for `scan create-issue` — pure string
 * building, no GitHub API calls, so this is fully unit-testable.
 *
 * Two kinds of markers get embedded as HTML comments (invisible in GitHub's
 * rendered view, present in the raw body):
 *   - one tracker marker, identifying which app+db this issue tracks, so
 *     `create-issue` can find its own issue on a re-run instead of creating
 *     a duplicate (or the wrong app/db's issue, in a repo scanning several).
 *   - one per-finding marker, right after each checklist line, so a later
 *     tool (phase 4's `ship start`) can map a checked GitHub box back to a
 *     specific table+action finding without parsing prose.
 */

const RISK_HEADINGS: Record<RiskLevel, string> = {
  critical: "Critical",
  high: "High",
  medium: "Medium",
  low: "Low / informational",
};

const RISK_ORDER: RiskLevel[] = ["critical", "high", "medium", "low"];

// HTML comments can't contain "--" — swap in a lookalike so paths/db names
// can't accidentally break the comment's syntax.
function sanitizeForComment(s: string): string {
  return s.replace(/-/g, "‐");
}

export function buildTrackerMarker(report: Pick<AppScanReport, "appDir" | "databaseName">): string {
  return `<!-- rls-guard:scan-tracker app=${sanitizeForComment(report.appDir)} db=${sanitizeForComment(report.databaseName)} -->`;
}

export function buildFindingMarker(table: string, action: string): string {
  return `<!-- rls-guard:finding table=${sanitizeForComment(table)} action=${sanitizeForComment(action)} -->`;
}

function isOpen(f: AppCrudFinding): boolean {
  return f.status === "open";
}

export function hasOpenFindings(report: AppScanReport): boolean {
  return report.findings.some(isOpen);
}

function callSitesText(f: AppCrudFinding): string {
  if (f.callSites.length === 0) return "(no longer in source)";
  return f.callSites.map((c) => `\`${c.file}:${c.line}\``).join(", ");
}

function renderOpenFinding(f: AppCrudFinding): string {
  return [
    `- [ ] **${f.table}.${f.action}** — ${f.summary} (${callSitesText(f)})`,
    `  ${buildFindingMarker(f.table, f.action)}`,
  ].join("\n");
}

function renderOpenGroup(risk: RiskLevel, findings: AppCrudFinding[]): string {
  const inGroup = findings.filter((f) => f.riskLevel === risk && isOpen(f));
  if (inGroup.length === 0) return "";
  return `### ${RISK_HEADINGS[risk]} (${inGroup.length})\n\n${inGroup.map(renderOpenFinding).join("\n")}`;
}

function renderHistoryRow(f: AppCrudFinding): string {
  const parts = [`**${f.table}.${f.action}** (${f.riskLevel}) — ${f.status}`];
  if (f.comment) parts.push(`"${f.comment}"`);
  if (f.resolvedAt) parts.push(`on ${new Date(f.resolvedAt).toLocaleDateString()}`);
  if (!f.detectedInLastScan) parts.push("_(no longer detected — kept for history)_");
  return `- ${parts.join(" — ")}`;
}

export function buildIssueTitle(report: AppScanReport): string {
  const openCount = report.findings.filter(isOpen).length;
  const suffix = `${report.appDir} (${report.databaseName})`;
  return openCount === 0 ? `rls-guard scan: all clear — ${suffix}` : `rls-guard scan: ${openCount} open finding(s) — ${suffix}`;
}

export function buildIssueBody(report: AppScanReport): string {
  const openFindings = report.findings.filter(isOpen);
  const historyFindings = report.findings.filter((f) => !isOpen(f));

  const lines: string[] = [
    buildTrackerMarker(report),
    "",
    `Auto-generated by \`rls-guard scan create-issue\`. Do not edit this body by hand — it will be overwritten on the next sync. Last synced from a scan generated ${report.generatedAt}.`,
    "",
    `App: \`${report.appDir}\` — DB: \`${report.databaseName}\``,
    "",
  ];

  if (openFindings.length === 0) {
    lines.push("**All clear** — no open findings as of the latest scan.");
  } else {
    lines.push(`${openFindings.length} open finding(s), grouped by risk level.`);
    lines.push("");
    for (const risk of RISK_ORDER) {
      const group = renderOpenGroup(risk, openFindings);
      if (group) lines.push(group, "");
    }
  }

  if (historyFindings.length > 0) {
    lines.push(
      "<details>",
      `<summary>Resolved / won't-fix (${historyFindings.length}) — click to expand</summary>`,
      "",
      ...historyFindings.map(renderHistoryRow),
      "",
      "</details>"
    );
  }

  return lines.join("\n").trimEnd() + "\n";
}
