import { createInterface } from "node:readline/promises";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { AppCrudFinding, AppScanReport, LiveSchema } from "../types.js";
import { generateFindingFixSql } from "./claude.js";
import { dryRunSql } from "./validate.js";
import { applyResolution } from "./scanReport.js";
import { syncScanIssue } from "./issueSync.js";
import { commentOnIssue, createPr } from "./githubIssue.js";
import * as git from "./gitOps.js";

function findingKey(f: { table: string; action: string }): string {
  return `${f.table}::${f.action}`;
}

/** The next open, auto-fixable finding not already skipped this session — null when there's nothing left to offer. */
export function nextFixableFinding(findings: AppCrudFinding[], skipped: Set<string>): AppCrudFinding | null {
  return findings.find((f) => f.status === "open" && f.autoFixable && !skipped.has(findingKey(f))) ?? null;
}

export function migrationFilePath(migrationsDir: string, finding: AppCrudFinding): string {
  const safeTable = finding.table.replace(/[^a-zA-Z0-9_]/g, "_");
  return path.join(migrationsDir, `${safeTable}_${finding.action}.sql`);
}

function branchName(finding: AppCrudFinding): string {
  const safe = `${finding.table}-${finding.action}`.replace(/[^a-zA-Z0-9/_-]/g, "-");
  return `rls-guard/fix-${safe}`;
}

export interface ShipStartOptions {
  report: AppScanReport;
  liveSchema: LiveSchema;
  databaseUrl: string;
  migrationsDir: string;
  repo?: string;
  /** Called after each finding is resolved, so progress is never lost to a mid-session interrupt. */
  onFindingResolved: (report: AppScanReport) => Promise<void>;
}

/**
 * Interactive remediation loop (phase 4, "ship start"). Per auto-fixable open finding:
 * show the plan (approval checkpoint 1) -> generate + dry-run the fix SQL -> show the
 * migration (approval checkpoint 2) -> write the migration file, commit/push/open a PR
 * -> mark the finding resolved and sync the GitHub issue. Any rejection or failed dry
 * run just skips that finding for the rest of this session (see PLAN.md phase 4).
 */
export async function runShipStart(opts: ShipStartOptions): Promise<void> {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const approve = async (question: string): Promise<boolean> => (await rl.question(question)).trim().toLowerCase() === "y";

  let report = opts.report;
  const skipped = new Set<string>();

  try {
    while (true) {
      const finding = nextFixableFinding(report.findings, skipped);
      if (!finding) {
        console.log("\nNo auto-fixable open findings left.");
        break;
      }

      console.log(`\n[${finding.riskLevel.toUpperCase()}] ${finding.table}.${finding.action}`);
      console.log(finding.summary);
      console.log(`Proposed fix: ${finding.recommendation}`);
      console.log(`Found at: ${finding.callSites.map((c) => `${c.file}:${c.line}`).join(", ") || "(no call sites recorded)"}`);

      if (!(await approve("\nApprove this plan? [y/n] "))) {
        console.log("Skipped — left open, won't be offered again this session.");
        skipped.add(findingKey(finding));
        continue;
      }

      console.log("Generating fix...");
      const sql = await generateFindingFixSql(finding, opts.liveSchema);

      console.log("Dry-running the fix against the live database (BEGIN ... ROLLBACK, nothing kept)...");
      const dryRun = await dryRunSql(opts.databaseUrl, sql);
      if (!dryRun.ok) {
        console.log(`Dry run FAILED (${dryRun.error}) — skipping this finding, won't be offered again this session.`);
        skipped.add(findingKey(finding));
        continue;
      }

      const filePath = migrationFilePath(opts.migrationsDir, finding);
      console.log(`\nDry run OK. Proposed migration (${filePath}):\n`);
      console.log(sql);

      if (!(await approve("\nApprove and open a PR? [y/n] "))) {
        console.log("Rejected — left open, won't be offered again this session.");
        skipped.add(findingKey(finding));
        continue;
      }

      await mkdir(path.dirname(filePath) || ".", { recursive: true });
      await writeFile(filePath, sql + "\n", "utf8");

      const branch = branchName(finding);
      await git.createBranch(branch);
      await git.stageAndCommit([filePath], `fix(rls): ${finding.table}.${finding.action}`);
      await git.push(branch);

      const prUrl = await createPr({
        title: `Fix RLS: ${finding.table}.${finding.action}`,
        body: [
          finding.summary,
          "",
          `**Fix:** ${finding.recommendation}`,
          "",
          `Generated by \`rls-guard ship start\`. This migration was dry-run (BEGIN ... ROLLBACK) against the ` +
            `database at ship-start time — it was never applied here. Review \`${filePath}\` and apply it through ` +
            `your normal deploy process before this actually takes effect.`,
        ].join("\n"),
        base: "main",
        repo: opts.repo,
      });
      console.log(`Opened PR: ${prUrl}`);

      await git.checkout("main");

      const { report: resolved } = applyResolution(report, {
        table: finding.table,
        action: finding.action,
        status: "resolved",
        comment: `Fixed via ${prUrl}`,
        resolvedAt: new Date().toISOString(),
      });
      report = resolved;
      await opts.onFindingResolved(report);

      const sync = await syncScanIssue(report, opts.repo);
      if (sync.issueNumber) {
        await commentOnIssue(sync.issueNumber, `Fixed \`${finding.table}.${finding.action}\`: ${prUrl}`, opts.repo);
      }
    }
  } finally {
    rl.close();
  }
}
